#Resource Icon, 1, "drive.ico"

#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Create test/dummy files"
#Resource Version$ "LegalCopyright",   "Copyright 2007-2017 BasicAware"
#Resource Version$ "OriginalFilename", "DummyFile.exe"
#Resource Version$ "ProductName",      "DummyFile"
#Resource Version$ "ProductVersion",   "2.0.1.0"
#Resource Version$ "FileVersion",      "2.0.1.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
